### ISSUE TITLE
nginx 1.0.8

### ISSUE THREAD

**Issue by rickytato** [yaoweibin/nginx_syslog_patch#1]
Seems not work with nginx 1.0.8:

I complied nginx with:

cd nginx-1.0.8
patch -p1 < ../yaoweibin-nginx_syslog_patch-afeea6d/syslog_1.0.6.patch 
./configure --prefix=/usr/local --with-http_addition_module --with-http_sub_module --with-http_realip_module --with-http_stub_status_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_scgi_module --without-http_uwsgi_module --without-http_memcached_module --without-select_module --add-module=/usr/local/src/yaoweibin-nginx_syslog_patch-afeea6d

and in nginx.conf:
syslog local6 nginx;

When restart:
nginx: [emerg] unknown directive "syslog" in /usr/local/nginx/conf/nginx.conf:5

**Comment by yaoweibin** [comment]
On 2011-10-2 15:56, rickytato wrote:

> Seems not work with nginx 1.0.8:
> 
> I complied nginx with:
> 
> cd nginx-1.0.8
> patch -p1<  ../yaoweibin-nginx_syslog_patch-afeea6d/syslog_1.0.6.patch
> ./configure --prefix=/usr/local --with-http_addition_module --with-http_sub_module --with-http_realip_module --with-http_stub_status_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_scgi_module --without-http_uwsgi_module --without-http_memcached_module --without-select_module --add-module=/usr/local/src/yaoweibin-nginx_syslog_patch-afeea6d
> 
> and in nginx.conf:
> syslog local6 nginx;
> 
> When restart:
> nginx: [emerg] unknown directive "syslog" in /usr/local/nginx/conf/nginx.conf:5
> 
> It's weird. I tested in my box. It's fine.

Have you updated your binary Nginx file?

## 

Weibin Yao

**Comment by rickytato** [comment]
Yes sorry, it's my fault; work perfectly!

**Comment by wkzhjz** [comment]
Hi , I've also met this question too. can show the reason ? or show the key conf of syslog, tks very much!

**Comment by yaoweibin** [comment]
What's this command show?
./nginx -V

**Comment by wkzhjz** [comment]
The nginx version is nginx/1.0.14 , and the info added in  nginx.conf :
  syslog local6 nginx;

   The error info is : unknown directive "syslog" in /data/server/nginx1/conf/nginx.conf: 12 

```
I'm not be familiar with syslog , so I can't be sure of that It's the issue of the patch or nginx ~ 
```

**Comment by wkzhjz** [comment]
I used rsyslog,and  in my rsyslog.cnf I just write that:

local6:\*    /data/logs/access.log

it's ok?

**Comment by yaoweibin** [comment]
On 2012/3/21 14:42, wkzhjz wrote:

> The nginx version is nginx/1.0.14 , and the info added in  nginx.conf :
>    rsyslog local6 nginx;
> Not the rsyslog, The directive is syslog
> 
> ```
> The error info is : unknown directive "syslog" in /data/server/nginx1/conf/nginx.conf: 12
> ```
> 
> Can you show me your nginx version? Use this command:

./nginx -V

**Comment by wkzhjz** [comment]
That's the info:

nginx version: nginx/1.0.14
built by gcc 4.5.3 (Debian 4.5.3-12) 
configure arguments: --prefix=/data/server/nginx1 --with-http_addition_module --with-http_sub_module --with-http_realip_module --with-http_stub_status_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_scgi_module --without-http_uwsgi_module --without-http_memcached_module --without-select_module --add-module=/data/software/install/syslog

**Comment by yaoweibin** [comment]
It seems ok. Can you show me your config?

**Comment by wkzhjz** [comment]
and I'm sorry , in fact I'm also tried 

syslog local6 nginx; 

I get the same error info

**Comment by wkzhjz** [comment]
sudo sbin/nginx -t -c conf/nginx.conf
nginx: [emerg] unknown directive "syslog" in /data/server/nginx1/conf/vhost/vhost_blk.dc.s.com.conf:12
nginx: configuration file /data/server/nginx1/conf/nginx.conf test failed

and in the conf , it wrote:
 syslog local6 nginx;

**Comment by yaoweibin** [comment]
Do you put the directive in the main block like this?

worker_processes 1;
syslog local6 nginx;

Please don't use this directive in the http block or server block.

**Comment by wkzhjz** [comment]
I see , that's it! 

  thks very much !
