### ISSUE TITLE
Feature Request: A program name for each vhost

### ISSUE THREAD

**Issue by ghost** [yaoweibin/nginx_syslog_patch#3]
I have 50 apache vhosts running on a cluster with central logging using rsyslog.
I'm using apache log piping capability to pipe logs for each vhosts with a uniq program name.
On rsyslog side, I'm filtering the logs using program names.

Now I have to move to nginx.
So can you please help me by adding the feature of a program name per vhost in this patch ?

**Comment by yaoweibin** [comment]
On 2012-8-3 21:34, Ashish Disawal wrote:

> I have 50 apache vhosts running on a cluster with central logging using rsyslog.
> I'm using apache log piping capability to pipe logs for each vhosts with a uniq program name.
> On rsyslog side, I'm filtering the logs using program names.
> 
> Now I have to move to nginx.
> So can you please help me by adding the feature of a program name per vhost in this patch ?

Can you try the Tengine 
(http://tengine.taobao.org/document/http_log.html)? We are maintaining 
this Nginx's fork. It can work for you.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yaoweibin/nginx_syslog_patch/issues/3

## 

Thanks,
-Weibin Yao
