### ISSUE TITLE
new tag including 1.2.0 patch

### ISSUE THREAD

**Issue by morfoh** [yaoweibin/nginx_syslog_patch#4]
Hi,
it would be nice if you could create a new "official" tag which would then include the patch for the nginx 1.2 series. This would simplify packaging or updating this addon.
Thanks a lot
Chris

**Comment by yaoweibin** [comment]
On 2012-11-13 18:52, Christian Wiese wrote:

> Hi,
> it would be nice if you could create a new "official" tag which would 
> then include the patch for the nginx 1.2 series. This would simplify 
> packaging or updating this addon.
> Thanks a lot
> Chris
> 
> OK. I'll do it tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/yaoweibin/nginx_syslog_patch/issues/4.

## 

Thanks,
-Weibin Yao

**Comment by morfoh** [comment]
That would be great!
Thank you

**Comment by yaoweibin** [comment]
On 2012/11/13 18:52, Christian Wiese wrote:

> Hi,
> it would be nice if you could create a new "official" tag which would 
> then include the patch for the nginx 1.2 series. This would simplify 
> packaging or updating this addon.
> Thanks a lot
> Chris
> 
> Done. See the new tag: https://github.com/yaoweibin/nginx_syslog_patch/tags

## 

Thanks
-YWB
