### ISSUE TITLE
nginx_syslog_patch in upstream?

### ISSUE THREAD

**Issue by rngadam** [yaoweibin/nginx_syslog_patch#6]
I was wondering; will this patch make it upstream eventually? 

What is preventing including this in the main nginx? 

Seems rather useful!

**Comment by yaoweibin** [comment]
You can see the reason here: http://forum.nginx.org/read.php?2,225811,225822#msg-225822

**Comment by rngadam** [comment]
Reading that thread, it sounds like FUD, no? Using rsyslogd, whether it is up or not, you can write to /dev/log. The only way to block the write is to suspend the rsyslogd thread... Plus, why couldn't this be made into a ./configure option and let users choose whether they want it or not? 

Anyway, I'll be testing nginx + syslog patch + rsyslogd. If the results are positive I'll ping the mailing list and ask them to reconsider.

**Comment by yaoweibin** [comment]
Thanks. If you want to have a try, we have supported syslog in our nginx fork: http://tengine.taobao.org/index.html . We have implemented syslog protocol internally which don't block the socket at all.

**Comment by josephholsten** [comment]
syslog is included in nginx plus (per http://nginx.com/products/)

I'll be annoying on the official tracking bug again: http://trac.nginx.org/nginx/ticket/95

**Comment by josephholsten** [comment]
as soon as it lets me log in again.

**Comment by yaoweibin** [comment]
Could you try tengine(http://tengine.taobao.org/document/http_log.html)? It supports syslog natively. I'm now one of developer of tengine.

**Comment by josephholsten** [comment]
If be happy to! We're mostly using nginx for passenger. Does it support passenger out of the box?

## 

http://josephholsten.com
