### ISSUE TITLE
syslog_1.3.11.patch doesn't apply to nginx-1.3.14 anymore

### ISSUE THREAD

**Issue by mrueg** [yaoweibin/nginx_syslog_patch#8]
patching file src/http/ngx_http_core_module.c
Hunk #1 FAILED at 1459.
Hunk #2 succeeded at 4867 (offset 54 lines).
Hunk #3 succeeded at 4885 (offset 54 lines).
Hunk #4 succeeded at 4924 (offset 54 lines).
1 out of 4 hunks FAILED -- saving rejects to file src/http/ngx_http_core_module.c.rej
patching file src/http/ngx_http_request.c
Hunk #1 FAILED at 441.
Hunk #2 FAILED at 1845.
2 out of 2 hunks FAILED -- saving rejects to file src/http/ngx_http_request.c.rej

see also
http://trac.nginx.org/nginx/changeset/5087/nginx

**Comment by yaoweibin** [comment]
fixed in https://github.com/yaoweibin/nginx_syslog_patch/commit/f42ef1187418a12b07813d5f36a84e0834f56b4c

**Comment by mrueg** [comment]
thanks, can you add a tag, too?

**Comment by yaoweibin** [comment]
On 2013/3/15 2:10, Manuel Rüger wrote:

> thanks, can you add a tag, too?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/yaoweibin/nginx_syslog_patch/issues/8#issuecomment-14919206.
> 
> done

## 

Thanks
-YWB
