### ISSUE TITLE
FreeBSD nginx 1.0.27 patch

### ISSUE THREAD

**Issue by davidone** [yaoweibin/nginx_syslog_patch#9]
Hi, I'm using FreeBSD and nginx 1.0.27 (well, I am trying to compile 1.0.28 but I'm encountering the same problem) but I don't understand what do I have to apply in order to use syslog patch.

Thanks,
d.

**Comment by yaoweibin** [comment]
What's your problem? Could you describe it more clearly?

**Comment by davidone** [comment]
Using the syslog-patch I don't see any message being sent to syslog.

I'm using the freebsd ports system, so I don't know if is a problem related to the patch or if the patch used in the ports is too old.

**Comment by yaoweibin** [comment]
Can you capture any UDP packet in the address of 127.0.0.1:514? This syslog patch will send the message to the program syslogd.

And can you show me your nginx.conf and syslog's config?

**Comment by davidone** [comment]
Well, If I use in nginx.conf:

```
syslog local6 nginx;
```

I have a syntax error:

```
# service nginx configtest
Performing sanity check on nginx configuration:
nginx: [emerg] unknown directive "syslog" in /usr/local/etc/nginx/nginx.conf:3
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
# 
```

Nginx is compiled:

```
# strings nginx | grep -i syslog
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx-error.log --user=www --group=www --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx-access.log --add-module=/usr/ports/www/nginx/work/ngx_cache_purge-2.1 --add-module=/usr/ports/www/nginx/work/agentzh-headers-more-nginx-module-27bcbd2 --with-http_stub_status_module --with-pcre --with-syslog --with-syslog-facility=LOG_LOCAL7
#
```

I'm using nginx-1.2.8 on a FreeBSD 9.1 amd64

**Comment by yaoweibin** [comment]
It seems that you don't use my patch. Where is the patch from?

**Comment by davidone** [comment]
I'm using the ports system, so the patch I'm using is from:
http://svnweb.freebsd.org/ports/head/www/nginx/files/extra-patch-syslog_support?view=log

2013/4/10 Weibin Yao(姚伟斌) notifications@github.com

> It seems that you don't use my patch. Where is the patch from?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yaoweibin/nginx_syslog_patch/issues/9#issuecomment-16182552
> .

## 

d.

**Comment by yaoweibin** [comment]
OK. I see. OSA changed the patch a little. Could you use my origin patch and test again? It works in my box.

**Comment by davidone** [comment]
Sorry for being so late but now everything is fine. Using version 1.4.4_3,1:

```
syslog local6 nginx;

http {
    more_set_headers    "Server: freebsd_rocks";
    server_names_hash_bucket_size 64;

    include             /usr/local/etc/nginx/mime.types;
    default_type        application/octet-stream;

    log_format upstream '"$remote_addr","$host",[$time_local],'
                        '"$request",S:[$status],$body_bytes_sent,"$http_referer",'
                        '"$http_user_agent","$http_x_forwarded_for","$upstream_addr",'
                        '"$upstream_cache_status","$upstream_response_time","$request_time"';

    access_log          syslog:notice upstream;
    error_log           syslog:notice;

[...]
```

Thanks,
d.
